### ISSUE TITLE
annotateit not responding

### ISSUE THREAD

**Issue by stephskardal** [openannotation/annotateit#19]
http://annotatorjs.org is not able to access annotateit, receiving a 500 error. @birdsarah is also seeing the same thing. She can provide additional details on her errors.

**Comment by birdsarah** [comment]
http://annotateit.org/api/search?user=bird is giving a 500 error as well as trying to go to my home page when I'm logged in to the site http://annotateit.org/user/home

**Comment by birdsarah** [comment]
@nickstenning took a look at this and almost everything is back up and running. uri searches are still broken though. e.g. http://annotateit.org/api/search?user=bird is fine but http://annotateit.org/api/search?uri=http%3A%2F%2Fannotatorjs.org%2F" is still giving the 500 error.

**Comment by gergely-ujvari** [comment]
For me both searches are working fine.

**Comment by birdsarah** [comment]
Yes, agreed, the uri search is working now.

**Comment by nickstenning** [comment]
There was latent brokenness, which I fixed this morning. I hadn't recreated the mappings for the "document" indices.
