### ISSUE TITLE
Do content-negotiation on public annotation endpoints

### ISSUE THREAD

**Issue by nickstenning** [openannotation/annotateit#4]
The public annotation view, e.g. http://annotateit.org/a/UJuT17yHTt-woB3N9pMktg should respond appropriately to `Accept: application/json` or explicit extensions, e.g. http://annotateit.org/a/UJuT17yHTt-woB3N9pMktg.json

**Comment by rufuspollock** [comment]
Just a note that I think @pudo did this rather nicely in a couple of other Flask projects (e.g. okfn/webstore) so we can perhaps borrow code from there :-)

**Comment by nickstenning** [comment]
Closed by f70a2c54ba706b135bfda5aa5975ebdda6562016.
