### ISSUE TITLE
Login should remember me forever

### ISSUE THREAD

**Issue by rufuspollock** [openannotation/annotateit#5]
I can always log out if I want to. Log me in forever by default (or at least give me the option to choose that).

**Comment by nickstenning** [comment]
I'm translating this in my head as "implement 'remember me'" functionality, with some persistence period that is reasonably long.

**Comment by rufuspollock** [comment]
@nickstenning that's right! Remember me functionality with a long default persistence period (I'd suggest forever!).

**Comment by nickstenning** [comment]
Wontfix.
